import 'dart:async';
import 'dart:io';
import 'package:dio/dio.dart';
import 'package:ecomerce_ieee/features/sign-up-logic/domain/core/sign_up_result.dart';

import '../../domain/core/sign_up_exception.dart';


Future<SignUpResult<T>> authApiExecution<T>({
  required Future<Response<dynamic>> request,
  required T Function(dynamic data) fromJson,
}) async {
  try {
    Response<dynamic> response = await request;
    return Success(fromJson(response.data));
  } on SocketException {
    return Failure(exception: NoInternetException());
  } on TimeoutException {
    return Failure(exception: NoInternetException());
  } on DioException catch (e) {
    if (e.response?.statusCode == 401) {
      return Failure(
          exception:
          UnauthorizedException(message: e.response?.data['message']));
    } else if (e.response?.statusCode == 404) {
      return Failure(exception: NotFound(message: e.response?.data['message']));
    } else if (e.response?.statusCode == 409) {
      return Failure(
          exception: ConflictException(message: e.response?.data['message']));
    } else if (e.response != null && e.response!.statusCode! >= 500) {
      return Failure(
          exception: ServerError(details: e.response!.data.toString()));
    } else {
      return Failure(exception: UnknownErrorException());
    }
  }
}
